### ISSUE TITLE
Modern dark/light mode switch functionality

### ISSUE THREAD

**Issue by UsmanTechJive** [mustakshif/Asri#134]
I'm wondering if implementing this dark/light mode switch would be possible in SiYuan?

![image](https://github.com/user-attachments/assets/82079cea-5573-4888-9589-7bb26208a45e)

[Website Reference](https://www.thecoderashok.com/blog/css-gradient-border-glowing-animation)

**Comment by mustakshif** [comment]
I'm not sure whether SiYuan has opened the mode switch API to developers (or whether they even need an API for that). Additionally, it looks like it would take up too much space in the top bar.

**Comment by UsmanTechJive** [comment]
Well, I've tried my best to achieve a similar effect, but I'm not able to replicate the smooth switching effect like your theme has. As you can see in the video, it's not really a smooth experience compared to your theme's default behavior.

https://github.com/user-attachments/assets/f4c16944-37c2-4d04-9e39-8973faa27a5b

I'm sharing this JS snippet with you so you can try it on your end and see if you can somehow fix the left-click switching between light/dark modes to match your theme's smoothness and animation. It would be super amazing if you could help with this.

```
function initializeSiyuanModernThemeSwitch() {
    const darkLightThemeModeObserver = new MutationObserver(() => {
        if (!document.getElementById('siyuan-modern-theme-switch')) {
            createThemeSwitch();
        }
    });

    async function updateTheme(newMode) {
        try {
            // Trigger the native theme switch 
            const menu = document.querySelector('.b3-menu.--list');
            if (menu) {
                const targetItem = menu.querySelector(newMode === 1 ? 
                    '.b3-menu__item[data-type="dark"]' : 
                    '.b3-menu__item[data-type="light"]');
                if (targetItem) {
                    targetItem.click();
                    return;
                }
            }

            // If menu not open, use API with full preservation
            const fullConfig = {
                ...window.siyuan.config.appearance,
                mode: newMode,
            };

            // Call API to update mode
            await fetch('/api/setting/setAppearance', {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                },
                body: JSON.stringify(fullConfig)
            });

            // Update local config
            window.siyuan.config.appearance.mode = newMode;

            // Refresh the page to apply theme properly
            window.location.reload();

        } catch (error) {
            console.error('Theme update failed:', error);
        }
    }

    function createThemeSwitch() {
        const originalSwitch = document.getElementById('barMode');
        if (!originalSwitch) return;

        const wrapper = document.createElement('div');
        wrapper.className = 'siyuan-theme-switch__wrapper toolbar__item';
        wrapper.id = 'siyuan-modern-theme-switch';
        
        const currentMode = window.siyuan.config.appearance.mode;
        wrapper.innerHTML = `
            <div class="siyuan-theme-switch">
                <div class="siyuan-theme-switch__option ${currentMode === 0 ? 'active' : ''}" data-mode="0">
                    <svg><use xlink:href="#iconLight"></use></svg>
                    Light
                </div>
                <div class="siyuan-theme-switch__option ${currentMode === 1 ? 'active' : ''}" data-mode="1">
                    <svg><use xlink:href="#iconDark"></use></svg>
                    Dark
                </div>
            </div>
        `;

        // Handle left click for theme toggle
        wrapper.addEventListener('click', (e) => {
            e.stopPropagation();
            
            // Get current and new mode
            const currentMode = window.siyuan.config.appearance.mode;
            const newMode = currentMode === 1 ? 0 : 1;
            
            // First update switch appearance
            wrapper.querySelectorAll('.siyuan-theme-switch__option').forEach(option => {
                option.classList.toggle('active', parseInt(option.dataset.mode) === newMode);
            });

            // Then update theme
            updateTheme(newMode);
        });

        // Handle right click for menu
        wrapper.addEventListener('contextmenu', (e) => {
            e.preventDefault();
            e.stopPropagation();
            
            const menuTrigger = document.querySelector('#barMode');
            if (menuTrigger) {
                menuTrigger.click();
            }
        });

        if (originalSwitch && originalSwitch.parentNode) {
            originalSwitch.style.display = 'none';
            originalSwitch.parentNode.insertBefore(wrapper, originalSwitch);
        }
    }

    // Styles
const style = document.createElement('style');
style.textContent = `
    .siyuan-theme-switch__wrapper {
        position: relative;
        display: inline-flex;
        align-items: center;
        background: rgba(0, 0, 0, 0.1);
        border-radius: 16px;
        padding: 2px;
        cursor: pointer;
        transition: all 0.3s cubic-bezier(0.4, 0, 0.2, 1);
        height: 24px;
        border: 1px solid rgba(0, 0, 0, 0.1);
    }

    .siyuan-theme-switch {
        display: flex;
        align-items: center;
        gap: 0;
        height: 100%;
        background: transparent;
    }

    .siyuan-theme-switch__option {
        display: flex;
        align-items: center;
        padding: 0 10px;
        border-radius: 14px;
        font-size: 11px;
        font-weight: 500;
        color: rgba(0, 0, 0, 0.6);
        transition: all 0.3s cubic-bezier(0.4, 0, 0.2, 1);
        height: 20px;
        user-select: none;
        position: relative;
        z-index: 1;
    }

    .siyuan-theme-switch__option.active {
        background: var(--b3-theme-background);
        color: var(--b3-theme-on-background);
        box-shadow: 0 1px 2px rgba(0, 0, 0, 0.1);
    }

    .siyuan-theme-switch__option svg {
        width: 12px;
        height: 12px;
        margin-right: 4px;
    }

    /* Hover effects */
    .siyuan-theme-switch__option:hover:not(.active) {
        background: rgba(0, 0, 0, 0.05);
    }

    /* Dark mode adjustments */
    [data-theme-mode="dark"] .siyuan-theme-switch__wrapper {
        background: rgba(255, 255, 255, 0.1);
        border-color: rgba(255, 255, 255, 0.1);
    }

    [data-theme-mode="dark"] .siyuan-theme-switch__option {
        color: rgba(255, 255, 255, 0.6);
    }

    [data-theme-mode="dark"] .siyuan-theme-switch__option:hover:not(.active) {
        background: rgba(255, 255, 255, 0.05);
    }

    [data-theme-mode="dark"] .siyuan-theme-switch__option.active {
        background: var(--b3-theme-background);
        color: var(--b3-theme-on-background);
        box-shadow: 0 1px 2px rgba(0, 0, 0, 0.2);
    }
`;
    document.head.appendChild(style);

    // Start observing
    darkLightThemeModeObserver.observe(document.body, {
        childList: true,
        subtree: true
    });

    // Initial creation
    createThemeSwitch();

    // Cleanup function
    return () => {
        darkLightThemeModeObserver.disconnect();
    };
}

// Start the script
initializeSiyuanModernThemeSwitch();
```

**Comment by UsmanTechJive** [comment]
> Additionally, it looks like it would take up too much space in the top bar.

You have a good point. We could just use the icons without text, which would make it slightly smaller.

**Comment by UsmanTechJive** [comment]
This is how I want it to be...

https://github.com/user-attachments/assets/cc5033a3-3f76-402c-bb23-3fac046c5e71

**Comment by mustakshif** [comment]
Wow... you've blown my mind once again! I'm amazed at how efficiently you make things happen. I have nothing but respect for your work!

Regarding the transition smoothness, I need to sleep now but I can quickly share some tips: I used the View Transition API and here's how I implemented it in my theme, for your reference:

https://github.com/mustakshif/Asri/blob/437b3e9725b927e93ec06ffbb957c9f3e01c9292/src/modules/modeTransition.ts#L1-L43

**Comment by UsmanTechJive** [comment]
> Wow... you've blown my mind once again! I'm amazed at how efficiently you make things happen. I have nothing but respect for your work!
> 
> Regarding the transition smoothness, I need to sleep now but I can quickly share some tips: I used the [View Transition API](https://developer.chrome.com/docs/web-platform/view-transitions) and here's how I implemented it in my theme, for your reference:
> 
> https://github.com/mustakshif/Asri/blob/437b3e9725b927e93ec06ffbb957c9f3e01c9292/src/modules/modeTransition.ts#L1-L43

Thank you! Your support means a lot to me. 

I checked your transition code and tweaked it a bit for fun. Here is an almost near to final version of the code. I'm still not sure about the switch style, and the window animation is just for fun lol maybe I will change it to the default look later. You can check this second version of the script snippet and let me know what you think of it.

Video:

https://github.com/user-attachments/assets/698de29a-7de7-47ea-a57f-9e00627fcdf5


Script:

```
// Initialize theme switch functionality and DOM observer
function initializeSiyuanModernThemeSwitch() {
    const darkLightThemeModeObserver = new MutationObserver(() => {
        if (!document.getElementById('siyuan-modern-theme-switch')) {
            createThemeSwitch();
        }
    });

    // Main theme update function with animation support
    async function updateTheme(newMode) {
        try {
            // Check for view transition support
            if (!document.startViewTransition) {
                fallbackUpdateTheme(newMode);
                return;
            }

            // Initialize view transition
            const transition = document.startViewTransition(async () => {
                const menu = document.querySelector('.b3-menu.--list');
                if (menu) {
                    const targetItem = menu.querySelector(newMode === 1 ? 
                        '.b3-menu__item[data-type="dark"]' : 
                        '.b3-menu__item[data-type="light"]');
                    if (targetItem) {
                        targetItem.click();
                        return;
                    }
                }

                // Prepare and update theme configuration
                const fullConfig = {
                    ...window.siyuan.config.appearance,
                    mode: newMode,
                };

                // Send theme update request to API
                await fetch('/api/setting/setAppearance', {
                    method: 'POST',
                    headers: {
                        'Content-Type': 'application/json',
                    },
                    body: JSON.stringify(fullConfig)
                });

                // Update theme in UI
                window.siyuan.config.appearance.mode = newMode;
                document.documentElement.setAttribute('data-theme-mode', newMode === 1 ? 'dark' : 'light');
                window.siyuan.config.appearance.themeJS && eval(window.siyuan.config.appearance.themeJS);
            });

            // Add Window transition animation styles (Optional - For Fun)
            const style = document.createElement('style');
            style.textContent = `
                ::view-transition-old(root),
                ::view-transition-new(root) {
                    animation-duration: 0.6s;
                    animation-timing-function: cubic-bezier(0.34, 1.56, 0.64, 1);
                }

                ::view-transition-old(root) {
                    animation: scale-out 0.6s cubic-bezier(0.34, 1.56, 0.64, 1);
                }
                ::view-transition-new(root) {
                    animation: scale-in 0.6s cubic-bezier(0.34, 1.56, 0.64, 1);
                }

                @keyframes scale-in {
                    from {
                        transform: scale(0.95);
                        opacity: 0;
                    }
                    to {
                        transform: scale(1);
                        opacity: 1;
                    }
                }

                @keyframes scale-out {
                    from {
                        transform: scale(1);
                        opacity: 1;
                    }
                    to {
                        transform: scale(1.05);
                        opacity: 0;
                    }
                }
            `;
            document.head.appendChild(style);

            await transition.finished;
            style.remove();

        } catch (error) {
            console.error('Theme update failed:', error);
            fallbackUpdateTheme(newMode);
        }
    }

    function fallbackUpdateTheme(newMode) {
        const fullConfig = {
            ...window.siyuan.config.appearance,
            mode: newMode,
        };

        fetch('/api/setting/setAppearance', {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
            },
            body: JSON.stringify(fullConfig)
        }).then(() => {
            window.location.reload();
        }).catch(error => {
            console.error('Theme update failed:', error);
        });
    }

    // Create and setup theme switch UI
    function createThemeSwitch() {
        const originalSwitch = document.getElementById('barMode');
        if (!originalSwitch) return;

        // Create switch wrapper
        const wrapper = document.createElement('div');
        wrapper.className = 'siyuan-theme-switch__wrapper toolbar__item';
        wrapper.id = 'siyuan-modern-theme-switch';
        
        // Set initial theme state
        const currentMode = window.siyuan.config.appearance.mode;
        wrapper.innerHTML = `
            <div class="siyuan-theme-switch">
                <div class="siyuan-theme-switch__option ${currentMode === 0 ? 'active' : ''}" data-mode="0">
                    <svg><use xlink:href="#iconLight"></use></svg>
                    <!-- Light -->
                </div>
                <div class="siyuan-theme-switch__option ${currentMode === 1 ? 'active' : ''}" data-mode="1">
                    <svg><use xlink:href="#iconDark"></use></svg>
                    <!-- Dark -->
                </div>
            </div>
        `;

        // Handle theme switch click
        wrapper.addEventListener('click', (e) => {
            e.stopPropagation();
            const currentMode = window.siyuan.config.appearance.mode;
            const newMode = currentMode === 1 ? 0 : 1;
            
            wrapper.querySelectorAll('.siyuan-theme-switch__option').forEach(option => {
                option.classList.toggle('active', parseInt(option.dataset.mode) === newMode);
            });

            updateTheme(newMode);
        });

        // Handle right-click menu
        wrapper.addEventListener('contextmenu', (e) => {
            e.preventDefault();
            e.stopPropagation();
            
            const menuTrigger = document.querySelector('#barMode');
            if (menuTrigger) {
                menuTrigger.click();
            }
        });

        // Replace original switch with new one
        if (originalSwitch && originalSwitch.parentNode) {
            originalSwitch.style.display = 'none';
            originalSwitch.parentNode.insertBefore(wrapper, originalSwitch);
        }
    }

    // Add theme switch styles
    const style = document.createElement('style');
    style.textContent = `
        .siyuan-theme-switch__wrapper {
            position: relative;
            display: inline-flex;
            align-items: center;
            background: var(--b3-theme-surface);
            border-radius: 16px;
            padding: 4px;
            cursor: pointer;
            height: 24px;
            border: 1px solid var(--b3-border-color);
            overflow: hidden;
        }

        .siyuan-theme-switch {
            display: flex;
            align-items: center;
            height: 100%;
            background: transparent;
            position: relative;
        }

        .siyuan-theme-switch::before {
            content: '';
            position: absolute;
            top: 0;
            left: 0;
            width: 50%;
            height: 100%;
            background: var(--b3-theme-primary);
            border-radius: 14px;
            transition: transform 0.6s cubic-bezier(0.34, 1.56, 0.64, 1);
            transform: translateX(0);
        }

        [data-theme-mode="dark"] .siyuan-theme-switch::before {
            transform: translateX(100%);
        }

        .siyuan-theme-switch__option {
            display: flex;
            align-items: center;
            padding: 0 10px;
            border-radius: 14px;
            font-size: 11px;
            font-weight: 500;
            color: var(--b3-theme-on-surface);
            height: 20px;
            user-select: none;
            position: relative;
            z-index: 1;
            flex: 1;
            justify-content: center !important;
            transition: color 0.3s ease;
        }

        .siyuan-theme-switch__option.active {
            color: var(--b3-theme-on-primary);
        }

        .siyuan-theme-switch__option svg {
            width: 12px;
            height: 12px;
            margin-right: 0;
            transition: transform 0.3s cubic-bezier(0.34, 1.56, 0.64, 1);
            display: block;
        }

        .siyuan-theme-switch__option:hover svg {
            transform: scale(1.2);
        }

        .siyuan-theme-switch__option:hover:not(.active) {
            color: var(--b3-theme-primary);
        }

        html[data-theme-mode="light"] .siyuan-theme-switch__wrapper {
            background: rgba(255, 255, 255, 0.8);
            backdrop-filter: blur(18px);
            border: 1px solid rgba(255, 255, 255, 0.4);
        }

        html[data-theme-mode="dark"] .siyuan-theme-switch__wrapper {
            background: rgba(28, 28, 30, 0.8);
            backdrop-filter: blur(18px);
            border: 1px solid rgba(255, 255, 255, 0.1);
        }

        .siyuan-theme-switch__option.active svg {
            filter: drop-shadow(0 1px 2px rgba(0, 0, 0, 0.3));
        }
    `;
    document.head.appendChild(style);

    // Setup view transition support
    const meta = document.createElement('meta');
    meta.name = 'view-transition';
    meta.content = 'same-origin';
    document.head.appendChild(meta);

    // Start observing DOM for theme switch
    darkLightThemeModeObserver.observe(document.body, {
        childList: true,
        subtree: true
    });

    // Initialize theme switch
    createThemeSwitch();

    // Cleanup function
    return () => {
        darkLightThemeModeObserver.disconnect();
    };
}

// Start the script
initializeSiyuanModernThemeSwitch();
```

**Comment by mustakshif** [comment]
Really appreciate you sharing the snippet! It runs perfectly on my end and helped me make improvements to my implementation. Here's what I've got now:


https://github.com/user-attachments/assets/73946aba-142e-4e7e-b238-71452fd10fb7



I decided to omit the toggle button as theme switching is typically an occasional action, but it's such a creative addition and I love how you implemented it!

**Comment by SamHanks94** [comment]
@mustakshif I'm looking for a theme like that one in your last comment. May I ask for its name?

**Comment by mustakshif** [comment]
> [@mustakshif](https://github.com/mustakshif) I'm looking for a theme like that one in your last comment. May I ask for its name?

It's Asri with `customize theme color` set to approximately `#6181FE` and `chroma` set to around `2.5x`

**Comment by SamHanks94** [comment]
> It's Asri with `customize theme color` set to approximately `#6181FE` and `chroma` set to around `2.5x`

I mean I need a dark theme like yours. I already have Asri but only its light mode can be customized. The dark mode is a simple dark screen with no option to customize:

<img width="1238" height="399" alt="Image" src="https://github.com/user-attachments/assets/b0180792-5a95-4ad1-b36c-bb19161397bd" />

However, I have more options than yours in the light mode:

<img width="1232" height="452" alt="Image" src="https://github.com/user-attachments/assets/2ca1a383-cfe7-4bcd-bc24-71681e751d7e" />

**Comment by mustakshif** [comment]
> I mean I need a dark theme like yours. I already have Asri but only its light mode can be customized. The dark mode is a simple dark screen with no option to customize:

You need to set dark theme to Asri as well, in Settings - Appearance. 

The options have increased as I've added more customizations to the theme since last year.
